service: robocode

provider:
  name: aws
  runtime: java8
  stage: dev
  profile: pavel
  region: eu-central-1
  memorySize: 1024
  timeout: 60
  logRetentionInDays: 14
  environment:
    DEBUG: true
    JAVA_TOOL_OPTIONS: '-DWORKINGDIRECTORY=/tmp'

package:
  artifact: 'target/robocode-1.9.3.5-lambda.zip'

functions:
  runBattle:
    handler: net.sf.robocode.service.RunBattleHandler
    events:
      - http:
          path: /runBattle
          method: post

